spring:
  application:
    name: sos
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT:27017}/filestorage?authSource=admin
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 55MB

server:
  port: 8080
  base-url: ${SERVER_BASE_URL}
  api-keys: ${SERVER_API_KEYS}

storage:
  root-path: ${STORAGE_ROOT_PATH}
  max-file-size: 52428800   # 50MB in bytes
  allowed-buckets-regex: "^[a-zA-Z0-9_-]+$"
  allowed-filename-regex: "^[a-zA-Z0-9._-]+$"
  max-bucket-name-length: 50