name: "[PROD] Publish Docker Image"

on:
  push:
    branches: main

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'corretto'
      -
        name: Build application
        run: ./gradlew build -x test
      -
        name: Login in ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and Push Docker image
        run: |
          docker buildx create --use --name mybuilder
          docker buildx build . --platform linux/amd64,linux/arm64 --tag ghcr.io/alves-dev/sos:latest --push
          docker buildx build . --platform linux/amd64,linux/arm64 --tag ghcr.io/alves-dev/sos:$(date +%Y%m%d) --push